# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
