# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190220_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=500)),
                ('degree', models.CharField(choices=[('B.Tech', 'Bachelor Of Technology'), ('M.Tech', 'Master Of Technology'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master Of Business Administration'), ('Class 10', 'High School'), ('Class 12', 'Higher Secondary School')], default='B.Tech', max_length=20)),
                ('year_of_starting', models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015')], default='2017', max_length=20)),
                ('year_of_completion', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2017', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default=None, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile', verbose_name=''),
        ),
    ]
