# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-21 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_account', models.CharField(max_length=10)),
                ('esi_account', models.CharField(max_length=10)),
                ('bank_account', models.CharField(max_length=10)),
                ('arrears', models.IntegerField()),
                ('basic_salary', models.IntegerField()),
                ('bonus_salary', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('diksha', models.IntegerField()),
                ('income_tax', models.IntegerField()),
                ('prof_tax', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.EmployeeDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('days_in_month', models.IntegerField()),
                ('present_days', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EmployeeDetails')),
            ],
        ),
    ]
