# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-23 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='arrears',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='bonus_salary',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='diksha',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='esi_account',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='pf_account',
        ),
        migrations.RemoveField(
            model_name='employeesalarydetails',
            name='prof_tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='days_in_month',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='period',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='present_days',
        ),
    ]
